### ISSUE TITLE
Change license from MIT to GPLv3+

### ISSUE THREAD

**Issue by maxrake** [phylum-dev/phylum-types#53]
## Description

The license for this repository/project needs to change from the current MIT license to the [GNU General Public License (GPL)](https://www.gnu.org/licenses/gpl-3.0-standalone.html) v3.0 or later.

## Additional Details

This change is directed towards all public repositories in the `phylum-dev` organization (with the exception of forked repos).

## Acceptance Criteria

- [ ] The license is changed to GPLv3+
- [ ] Documentation is updated

**Comment by kylewillmon** [comment]
In order to encourage the use of this library and the Phylum API, we have decided to keep the MIT license for this code.
