### ISSUE TITLE
Refactor `PackageType` into common?

### ISSUE THREAD

**Issue by ein-tier** [phylum-dev/phylum-types#56]
While adding support for Golang I needed to extend the `PackageType` enum here and noticed that it feels a lot like the `Ecosystem` enum in common. Perhaps the `PackageType::language(...)` function doesn't map 100% onto the `SourceFileType` enum in common, however, I think we could easily introduce a `Language` enum and map between the two similar to what is done here.

I definitely don't have all the history/context for how this repo is used – but putting this out there as it seems like it would simplify things and make it easier to keep them consistent.

**Comment by matt-phylum** [comment]
I think it'd need to be the other way around. common is an internal repository so we can't move anything from here to there if it's used by other public repositories like our CLI.

**Comment by ein-tier** [comment]
@matt-phylum Thanks! I hadn't grasped the difference between this and common – it makes sense that we need this here because it's public.

And now thinking more about it, we probably don't want to migrate the ecosystem, etc, enums into here because we would need to merge changes to those enums during development and doing so would expose information about upcoming features and such.

So a tiny bit of duplication but with good reason – closing!
