### ISSUE TITLE
Change `rubygems` package type to `gem`

### ISSUE THREAD

**Issue by kylewillmon** [phylum-dev/phylum-types#61]
To be consistent with PURL, the `PackageType` enum should use `gem` instead of `rubygems`

_Originally posted by @kylewillmon in https://github.com/phylum-dev/cli/pull/805#issuecomment-1310799841_

**Comment by matt-phylum** [comment]
I don't think this is worth it. `PackageType` IDs are persisted to some older database tables and changing the IDs will break some database queries unless we migrate those tables at the same time.

**Comment by cd-work** [comment]
Yeah pretty much every Phylum application relies on this too. If we ever want to do this it'll probably have to be an alias first, then we can maybe eventually swap the alias to be the default and make the former default the alias.

**Comment by kylewillmon** [comment]
I had completely forgotten about this issue... This was in the early days of our switch to PURLs and before the `purl` crate existed. At this point, I do not think any changes to `PackageType` in this repository make sense.

For new code or significantly refactored code, we will be using types from the `purl` crate where this is not an issue.
